---
all:
  children:
    k3s_cluster:
      children:
        k3s_server:
          hosts:
            control-plane:
              ansible_host: 32.197.184.131
              private_ip: 10.0.1.79

        k3s_agents:
          hosts:
            worker-1:
              ansible_host: 44.192.100.47
              private_ip: 10.0.1.217

            worker-2:
              ansible_host: 54.147.102.169
              private_ip: 10.0.1.6
